### ISSUE TITLE
本格的なROMを動かす

### ISSUE THREAD

**Issue by kigh-ota** [sacchie/gbem#21]
https://hh.gbdev.io/game/shock-lobster

- [x] cartrige type $03 に対応する

**Comment by kigh-ota** [comment]
Cartridge Type = $03 | MBC1+RAM+BATTERY
ROM size = $00: 32 KiB	2 (no banking)
RAM size = $02 | 8 KiB | 1 bank

TODO: https://gbdev.io/pandocs/MBC1.html

```
cartridgeType: 0x3, romSize: 0x0, ramSize: 0x2)
Exception in thread "main" java.lang.RuntimeException: Invalid address: 0x2000
	at State$memory$1.set8(State.kt:285)
	at cpu.RunKt.run(run.kt:422)
	at MainKt.loop(main.kt:32)
	at MainKt.main(main.kt:84)
```

**Comment by kigh-ota** [comment]
2024/3/12

色々やって、haltでストップしている。画面は真っ白
```
-------------------------------------------- 0x1e5a: OpLdFromIoPort(d=0x48)
-------------------------------------------- 0x1e5c: OpSraR8(r=D)
-------------------------------------------- 0x1e5e: OpRrA()
-------------------------------------------- 0x1e5f: OpSraR8(r=D)
-------------------------------------------- 0x1e61: OpRrA()
-------------------------------------------- 0x1e62: OpPushR16(r=AF)
-------------------------------------------- 0x1e63: OpPushR16(r=BC)
-------------------------------------------- 0x1e64: OpRstN8(n=N_08)
------------------------------------------- 0x8: OpLdR8D8(r=A, d=0x1)
------------------------------------------- 0xa: OpLdToIoPort(d=0x94)
------------------------------------------- 0xc: OpHalt()
```

**Comment by hmaeta** [comment]
ここで止まったように見える:
https://github.com/tbsp/shock-lobster/blob/600c8e332881277304c3b0b593d9eeb11d6a8b60/src/vectors.asm#L27-L32

**Comment by hmaeta** [comment]
putSpritePixelsForScanlineInViewportToBufferを速攻returnすると下のような表示になった。
![image](https://github.com/sacchie/gbem/assets/12731394/c938f910-c81b-4423-a730-f19773d2c99c)

この海藻  (と以後、呼称する) は現状2つのみ表示される。
速攻returnでは上記の通り0なためは、これはspliteで実装されてそう。

この画面では海藻が4つ出るのが正しい。
現状2つのみということは、このsplite実装がミスしていそう。

4つの海藻のうち2つはshock lobsterの文字の後ろ側に表示されていて、これが表示されていない。
backgroundより裏側のspliterが表示されてなさそう。

drawBackgroundForScanlineInViewportをコメントアウトしたら海藻が4つ表示された。
透明色が考慮されてない？
bg -> window -> spliteという描画の順番がおかしい？
たしか描画の順番はサボっていた気がする。

**Comment by kigh-ota** [comment]
https://github.com/tbsp/shock-lobster/blob/master/src/room_title/room_title.asm#L386
海藻で合ってるらしい

**Comment by kigh-ota** [comment]
これでタイトル画面だけは表示が正しくなりそう
https://github.com/sacchie/gbem/commit/fc961fb28a3cf13e96e09172dd21422e5d87c6b4

その後の画面はまだ直ってない

**Comment by kigh-ota** [comment]
BG/Window/Spriteの描画ON/OFFをトグルするデバッグ機能とかあると良いかも

**Comment by kigh-ota** [comment]
2024-04-02

- BG/Windowとスプラインとの描画順序を修正→タイトル画面は正常に
- その次の画面がおかしい（左：われわれ、右：正解）
  - Window描画のY座標がおかしそうに見える

<img width="1000" alt="Screenshot 2024-04-02 at 20 05 14" src="https://github.com/sacchie/gbem/assets/459628/bb824b5b-c6e7-400b-bd23-f2c982ca29fa">

**Comment by hmaeta** [comment]
左上のspriteと右下のspriteが変わっている。
正解によるとこれは同一のものになるべき。
![image](https://github.com/sacchie/gbem/assets/12731394/3b4cac52-34e6-44c7-8e3b-b6666c1314b1)

OamDataを見たところ、titleIdは一致している。
```
0 OAM data: OamData(yPosition=39, xPosition=16, tileId=25, attributes=0)
1 OAM data: OamData(yPosition=47, xPosition=24, tileId=25, attributes=96)
2 OAM data: OamData(yPosition=127, xPosition=136, tileId=26, attributes=16)
```

26が「A」のタイルなので、25をflipしようとして26に侵入した？

**Comment by hmaeta** [comment]
![image](https://github.com/sacchie/gbem/assets/12731394/feb5acae-9e01-4704-9e36-6a3ec379a8ed)

winを非表示にしてbgとspriteだけ表示にしたもの。
Highが正しい位置に出ている。これはbgで描画されたもの。

winとbgでタイルの取り違えが起きてる？

**Comment by kigh-ota** [comment]
<img width="462" alt="Screenshot 2024-04-23 at 18 29 54" src="https://github.com/sacchie/gbem/assets/459628/b219dfc4-d65a-4db1-8186-8573a71c3263">

**Comment by kigh-ota** [comment]
2024/4/23

### TODO

- defines.asm `.waitVRAM` を読んでて気付いた
  - [x] STAT (FF41) のLY=LYC比較とSTAT interruptの実装
  - [x] STAT (FF41) の bit1-0 PPU Mode の実装
  - [x] STAT のbit2-0 は readonlyにする必要がある（今は全部setしてる）
  - [ ] PPU Modeに応じてVRAMなどへのR/Wが無効になったりする仕様の実装 

### わかったこと

- "vector" は割り込み要因のこと
- room_status.asm:242 の `StatusRasterTable` に、割り込みパラメータの`LYC`の値が入ってそう。その値は vectors.asm:124 の STAT handler で触ってそう（詳細はわからない）
- 現時点だと、↑のTODOの中では LY=LYC による割り込みを実装するのが確度高そう

**Comment by hmaeta** [comment]
LY=LYCの比較とSTAT interruptを実装したところ、改善が見られた:
![image](https://github.com/sacchie/gbem/assets/12731394/dc0a9981-ac06-4320-9ee5-a9f9d8f127b0)

**Comment by kigh-ota** [comment]
メモ
ループ中で何回に1回drawScanlineすべきか？の概算

- https://gbdev.io/pandocs/Rendering.html から、描画1"dot"が4.19MHzの1cycleに対応。また1scanlineは456dot
- https://gbdev.io/pandocs/Specifications.html → 4.19MHzはCPU frequencyと一致
- CPUは1byte読むのに 4 clock cycleかかるのだった → 1scanlineの描画は、456 / 4 = 114 byte 読む時間で行われる
- いま、雑実装で、1ループ中に2byte分と決め打っているので、114 / 2 = 57回ループに1回 drawScanlineすればタイマーとの整合性が取れている状態

**Comment by hmaeta** [comment]
次はgetCycleCountを実装して描画結果が変わるか確認。

**Comment by kigh-ota** [comment]
今回：
Opのcycle countを真面目に実装したが見た目は変わらなかった

次回：
https://github.com/Baekalfen/PyBoy/blob/master/pyboy/core/lcd.py#L134
あたりを参考に、LCDのrenderingにPPU Modeなどを考慮してちゃんと実装する

**Comment by kigh-ota** [comment]
次回：
state.ppuMode から STAT register や OAM アクセス制限 を実装する

**Comment by hmaeta** [comment]
startの下に線が出るようになっていた。

![image](https://github.com/sacchie/gbem/assets/12731394/434a78c0-7fb1-41a3-b7a9-6565659efbb6)

**Comment by hmaeta** [comment]
今回:
STAT register の対応をした

次回：
STAT interrupts (mode 0~2)、 OAM アクセス制限 を実装する

**Comment by kigh-ota** [comment]
STAT interrupts 残り実装しても変わらず

https://github.com/mattcurrie/dmg-acid2 を久しぶりに通してみる
<img width="592" alt="スクリーンショット 2024-07-09 18 42 52" src="https://github.com/sacchie/gbem/assets/459628/aa7a762c-ef32-4451-9c21-d74cce682c61">

いくつかFailure Exampleに当てはまるが、まず

> Eye displayed instead of right chin	Window internal line counter

を直す

↓

結果、改善したように見える

<img width="592" alt="スクリーンショット 2024-07-09 19 27 19" src="https://github.com/sacchie/gbem/assets/459628/e23f2572-e113-4a11-92cf-de5f3923e6f1">
<img width="592" alt="スクリーンショット 2024-07-09 19 29 19" src="https://github.com/sacchie/gbem/assets/459628/38c112c1-5c57-4e65-b848-52b6f4d09455">
<img width="592" alt="スクリーンショット 2024-07-09 19 29 53" src="https://github.com/sacchie/gbem/assets/459628/74e8e3fc-59a1-466f-88a6-16b3438b7186">

**Comment by kigh-ota** [comment]
TODO

- dmg-acid2 test rom
  - [x] Tongue visible	Object Enable (bit 1)
  - [x] Right mole visible	Object Priority Same X Coordinate
  - [x] Half of mouth missing	Bit 0 of tile index for 8x16 objects should be ignored
- [x] 一部のscanlineが描画されてない

**Comment by hmaeta** [comment]
> dmg-acid2 test rom

この対応はすべて`forEachSpritePixelForScanlineInViewportToBuffer`の内部実装を変えるだけで済んだ。
つまり`forEachSpritePixelForScanlineInViewportToBuffer`の切り方がよかったということのはず。
